/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout.index'
import { Route as LayoutCardRouteImport } from './routes/_layout.card'
import { Route as LayoutDailyRouteImport } from './routes/_layout.daily'
import { Route as LayoutDictationRouteImport } from './routes/_layout.dictation'
import { Route as LayoutGrowthRouteImport } from './routes/_layout.growth'
import { Route as LayoutJukeboxRouteImport } from './routes/_layout.jukebox'
import { Route as LayoutMeRouteImport } from './routes/_layout.me'
import { Route as LayoutPrintRouteImport } from './routes/_layout.print'
import { Route as LayoutReviewRouteImport } from './routes/_layout.review'
import { Route as LayoutWordsRouteImport } from './routes/_layout.words'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCardRoute = LayoutCardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDailyRoute = LayoutDailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDictationRoute = LayoutDictationRouteImport.update({
  id: '/dictation',
  path: '/dictation',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGrowthRoute = LayoutGrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutJukeboxRoute = LayoutJukeboxRouteImport.update({
  id: '/jukebox',
  path: '/jukebox',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMeRoute = LayoutMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPrintRoute = LayoutPrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutReviewRoute = LayoutReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWordsRoute = LayoutWordsRouteImport.update({
  id: '/words',
  path: '/words',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/card': typeof LayoutCardRoute
  '/daily': typeof LayoutDailyRoute
  '/dictation': typeof LayoutDictationRoute
  '/growth': typeof LayoutGrowthRoute
  '/jukebox': typeof LayoutJukeboxRoute
  '/me': typeof LayoutMeRoute
  '/print': typeof LayoutPrintRoute
  '/review': typeof LayoutReviewRoute
  '/words': typeof LayoutWordsRoute
}
export interface FileRoutesByTo {
  '/card': typeof LayoutCardRoute
  '/daily': typeof LayoutDailyRoute
  '/dictation': typeof LayoutDictationRoute
  '/growth': typeof LayoutGrowthRoute
  '/jukebox': typeof LayoutJukeboxRoute
  '/me': typeof LayoutMeRoute
  '/print': typeof LayoutPrintRoute
  '/review': typeof LayoutReviewRoute
  '/words': typeof LayoutWordsRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/card': typeof LayoutCardRoute
  '/_layout/daily': typeof LayoutDailyRoute
  '/_layout/dictation': typeof LayoutDictationRoute
  '/_layout/growth': typeof LayoutGrowthRoute
  '/_layout/jukebox': typeof LayoutJukeboxRoute
  '/_layout/me': typeof LayoutMeRoute
  '/_layout/print': typeof LayoutPrintRoute
  '/_layout/review': typeof LayoutReviewRoute
  '/_layout/words': typeof LayoutWordsRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/card'
    | '/daily'
    | '/dictation'
    | '/growth'
    | '/jukebox'
    | '/me'
    | '/print'
    | '/review'
    | '/words'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/card'
    | '/daily'
    | '/dictation'
    | '/growth'
    | '/jukebox'
    | '/me'
    | '/print'
    | '/review'
    | '/words'
    | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/card'
    | '/_layout/daily'
    | '/_layout/dictation'
    | '/_layout/growth'
    | '/_layout/jukebox'
    | '/_layout/me'
    | '/_layout/print'
    | '/_layout/review'
    | '/_layout/words'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/card': {
      id: '/_layout/card'
      path: '/card'
      fullPath: '/card'
      preLoaderRoute: typeof LayoutCardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/daily': {
      id: '/_layout/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof LayoutDailyRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dictation': {
      id: '/_layout/dictation'
      path: '/dictation'
      fullPath: '/dictation'
      preLoaderRoute: typeof LayoutDictationRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/growth': {
      id: '/_layout/growth'
      path: '/growth'
      fullPath: '/growth'
      preLoaderRoute: typeof LayoutGrowthRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/jukebox': {
      id: '/_layout/jukebox'
      path: '/jukebox'
      fullPath: '/jukebox'
      preLoaderRoute: typeof LayoutJukeboxRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/me': {
      id: '/_layout/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof LayoutMeRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/print': {
      id: '/_layout/print'
      path: '/print'
      fullPath: '/print'
      preLoaderRoute: typeof LayoutPrintRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/review': {
      id: '/_layout/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof LayoutReviewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/words': {
      id: '/_layout/words'
      path: '/words'
      fullPath: '/words'
      preLoaderRoute: typeof LayoutWordsRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutCardRoute: typeof LayoutCardRoute
  LayoutDailyRoute: typeof LayoutDailyRoute
  LayoutDictationRoute: typeof LayoutDictationRoute
  LayoutGrowthRoute: typeof LayoutGrowthRoute
  LayoutJukeboxRoute: typeof LayoutJukeboxRoute
  LayoutMeRoute: typeof LayoutMeRoute
  LayoutPrintRoute: typeof LayoutPrintRoute
  LayoutReviewRoute: typeof LayoutReviewRoute
  LayoutWordsRoute: typeof LayoutWordsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutCardRoute: LayoutCardRoute,
  LayoutDailyRoute: LayoutDailyRoute,
  LayoutDictationRoute: LayoutDictationRoute,
  LayoutGrowthRoute: LayoutGrowthRoute,
  LayoutJukeboxRoute: LayoutJukeboxRoute,
  LayoutMeRoute: LayoutMeRoute,
  LayoutPrintRoute: LayoutPrintRoute,
  LayoutReviewRoute: LayoutReviewRoute,
  LayoutWordsRoute: LayoutWordsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
