#!/usr/bin/env node
/**
 * 构建期把 public/units 的 catalog 数据内联成 TS 模块。
 * minitool 离线规范：运行时禁 fetch —— manifest/content/song 全部打进 JS bundle。
 * 由 package.json 的 dev/build 前缀调用；输出 src/data/catalog.generated.ts（勿手改）。
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const unitsDir = join(root, "public", "units");
const outFile = join(root, "src", "data", "catalog.generated.ts");

const HEADER =
  "/* AUTO-GENERATED by scripts/gen_catalog.mjs — DO NOT EDIT. */\n" +
  "export type EmbeddedUnit = { content: unknown; song: unknown; textbook: unknown };\n";

function readJson(p) {
  try {
    return JSON.parse(readFileSync(p, "utf8"));
  } catch {
    return null;
  }
}

const manifestPath = join(unitsDir, "manifest.json");
let manifest = existsSync(manifestPath) ? readJson(manifestPath) : null;

// 离线分包：CATALOG_UNITS=u01,u02 时只嵌入列出的单元（manifest 同步过滤）。
// 未设置时嵌入 public/units 全量（dev / 合并包）。
const onlyRaw = (process.env.CATALOG_UNITS || "").trim();
const onlySet = onlyRaw
  ? new Set(onlyRaw.split(",").map((s) => s.trim()).filter(Boolean))
  : null;
if (onlySet && manifest && Array.isArray(manifest.grades)) {
  manifest = {
    ...manifest,
    grades: manifest.grades
      .map((g) => ({
        ...g,
        units: (g.units ?? []).filter((u) => onlySet.has(u.id)),
      }))
      .filter((g) => (g.units ?? []).length > 0),
  };
}

let out;
let unitCount = 0;
if (!manifest || !Array.isArray(manifest.grades) || manifest.grades.length === 0) {
  out = `${HEADER}export const EMBEDDED_CATALOG: {\n  manifest: unknown;\n  units: Record<string, EmbeddedUnit>;\n} | null = null;\n`;
} else {
  const units = {};
  for (const grade of manifest.grades) {
    for (const u of grade.units ?? []) {
      if (onlySet && !onlySet.has(u.id)) continue;
      unitCount += 1;
      const base = join(unitsDir, u.id);
      units[u.id] = {
        content: readJson(join(base, "content.json")),
        song: readJson(join(base, "song", "song.json")),
        textbook: readJson(join(base, "song", "textbook_lyrics.json")),
      };
    }
  }
  const payload = JSON.stringify({ manifest, units });
  out = `${HEADER}export const EMBEDDED_CATALOG: {\n  manifest: unknown;\n  units: Record<string, EmbeddedUnit>;\n} | null = ${payload};\n`;
}

writeFileSync(outFile, out, "utf8");
console.log(`[gen_catalog] ${unitCount} unit(s) -> ${outFile} (${Buffer.byteLength(out)} bytes)`);
